#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 20 02:59:52 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=18
shaderPack=BSL_v10.0.zip
