name = "Cobblemon Dist"
author = "Fett"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c8352a8efa5c41844afe7385b85e4c9bf29aed58b151bb0cf36bd90dc88c321"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
