name = "Cobblemon Dist"
author = "Fett"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0eef9e0450fdc87117d2e78dfb4b9efa127e54e3bea0bd2a95d84c926860d6e1"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
