name = "Cobblemon Dist"
author = "Fett"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "816da798f28283967345c46f0cce8bcc46899d8a008b77aacbe2e4f7d2964f99"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
